baseURL = "https://gitee.com/yu_weibo/learning-machine.git"
languageCode = "zh-cn"
title = "汉字学习卡片游戏"
theme = "hugo-theme-stack"

# 静态文件配置
staticDir = ["dist"]

# 菜单配置
[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "游戏"
    url = "/game"
    weight = 2

# 参数配置
[params]
  description = "一个基于React和TypeScript的汉字学习卡片游戏"
  author = "Your Name"
  
# 构建配置
[build]
  writeStats = true
  
# 输出配置
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# 标记配置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
    guessSyntax = true
    noClasses = false

# 多语言配置
[languages]
  [languages.zh-cn]
    languageName = "简体中文"
    weight = 1
    title = "汉字学习卡片游戏"
    [languages.zh-cn.params]
      description = "一个基于React和TypeScript的汉字学习卡片游戏"