baseURL = "https://your-username.github.io/your-repo-name"
languageCode = "zh-cn"
title = "汉字学习卡片游戏"

# 静态文件配置
# 只包含 static 目录，避免与 webpack 输出冲突
staticDir = ["static"]

# 菜单配置
[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

[[menu.main]]
    name = "开始游戏"
    url = "/dist/game.html"
    weight = 2

# GitHub Pages 配置
[params]
  description = "一个有趣的汉字学习卡牌游戏，通过图片和声音帮助学习汉字"
  author = "Your Name"
  keywords = ["汉字", "学习", "卡牌游戏", "教育"]
  
# 构建配置
[build]
  writeStats = true
  
# 输出配置
[outputs]
  home = ["HTML", "RSS"]
  
# 标记配置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true