baseURL = "https://yuweibor.github.io/learning-machine"
languageCode = "zh-cn"
title = "汉字学习卡片游戏"
# theme = "hugo-theme-stack"  # 使用自定义布局，不需要主题

# 静态文件配置
staticDir = ["dist"]

# 菜单配置
[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "游戏"
    url = "/game"
    weight = 2

# GitHub Pages 配置
[params]
  description = "一个有趣的汉字学习卡牌游戏，通过图片和声音帮助学习汉字"
  author = "Your Name"
  keywords = ["汉字", "学习", "卡牌游戏", "教育"]
  
# 构建配置
[build]
  writeStats = true
  
# 输出配置
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# 标记配置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
    guessSyntax = true
    noClasses = false

# 多语言配置
[languages]
  [languages.zh-cn]
    languageName = "简体中文"
    weight = 1
    title = "汉字学习卡片游戏"
    [languages.zh-cn.params]
      description = "一个基于React和TypeScript的汉字学习卡片游戏"